from importlib.metadata import PackageNotFoundError, version  # pragma: no cover

try:
    # Change here if project is renamed and does not equal the package name
    dist_name = "uclid5-api"
    __version__ = version(dist_name)
except PackageNotFoundError:  # pragma: no cover
    __version__ = "unknown"
finally:
    del version, PackageNotFoundError

import z3

from .expr import (
    FALSE,
    TRUE,
    And,
    Array,
    ArrayVal,
    BitVec,
    BitVecVal,
    Bool,
    BoolVal,
    BVVal,
    Conjunction,
    Disjunction,
    If,
    Implication,
    Implies,
    Int,
    IntVal,
    Ite,
    Negation,
    Not,
    Or,
    Real,
    RealVal,
    bv,
    bv_val,
    false,
    prime,
    true,
)
from .module import Module
from .printer import UCLIDFormatter
from .statements import ConcurrentBlock, SequentialBlock
from .types import (
    ArraySort,
    BitVecSort,
    BooleanSort,
    BoolSort,
    BVSort,
    IntegerSort,
    RealSort,
    array,
    array_sort,
    bitvector,
    bitvector_sort,
    bool_sort,
    boolean,
    boolean_sort,
    bv_sort,
    datatype,
    enum,
    integer,
    integer_sort,
    real,
    real_sort,
    record,
    sort,
    this,
)
from .verify import bmc, induction

z3.z3printer._Formatter = UCLIDFormatter()

__all__ = [
    "Module",
    "integer",
    "real",
    "boolean",
    "array",
    "bitvector",
    "enum",
    "record",
    "datatype",
    "this",
    "sort",
    "prime",
    "Or",
    "And",
    "Implies",
    "Not",
    "Ite",
    "If",
    "induction",
    "bmc",
    "SequentialBlock",
    "ConcurrentBlock",
    "Bool",
    "Int",
    "Real",
    "BitVec",
    "Array",
    "TRUE",
    "FALSE",
    "true",
    "false",
    "bv",
    "bv_val",
    "BoolVal",
    "IntVal",
    "RealVal",
    "BitVecVal",
    "BVVal",
    "ArrayVal",
    "Conjunction",
    "Disjunction",
    "Implication",
    "Negation",
    "BooleanSort",
    "BoolSort",
    "IntegerSort",
    "RealSort",
    "BitVecSort",
    "BVSort",
    "array_sort",
    "boolean_sort",
    "bool_sort",
    "integer_sort",
    "real_sort",
    "bitvector_sort",
    "bv_sort",
    "ArraySort",
]
